### ISSUE TITLE
See if can be made official?

### ISSUE THREAD

**Issue by Merith-TK** [RuiNtD/PrismLauncherPortable#1]
So what would prevent this from being made into officially supported??

**Comment by RuinTD** [comment]
You mean officially supported by PortableApps.com? Literally all I’m waiting for is for their forums to stop being dead. :/

https://portableapps.com/node/68588

**Comment by Merith-TK** [comment]
I mean like from Prism for their portable builds

**Comment by RuinTD** [comment]
I mean, there's nothing wrong with Prism Launcher's portable builds. They work very similarly to MultiMC and many other portable software. My PortableApps.com version is meant to be installed to a flash drive, where the [PortableApps.com Platform](https://portableapps.com/download) can automatically update Java for you. This version also allows for easier updates than the official portable build, but [that will be changing pretty soon](https://github.com/PrismLauncher/PrismLauncher/pull/1268).

Either way, I'm not a developer for Prism Launcher, so I have no say in how they handle their portable builds. My version is already listed on their download page but if you think they should do more, you could probably bring it up on their [Discord or Reddit](https://prismlauncher.org/#get-involved).
